package errs

import "errors"

var (
	ErrNotFound      = errors.New("not found")
	ErrDuplicate     = errors.New("duplicate")
	ErrEmailTaken    = errors.New("email already registered")
	ErrInvalidJSON   = errors.New("invalid json body")
	ErrValidation    = errors.New("validation failed")
	ErrUnauthorized  = errors.New("unauthorized")
	ErrInvalidCreds  = errors.New("invalid email or password")
	ErrInvalidRole   = errors.New("invalid platform role")
	ErrWeakPassword  = errors.New("password must be at least 8 characters")
	ErrEmptyEmail    = errors.New("email is required")
	ErrEmptyName     = errors.New("full name is required")
	ErrInvalidToken  = errors.New("invalid token")
	ErrForbidden     = errors.New("forbidden")
	ErrNotOwner      = errors.New("not owner of hackathon")
	ErrCannotDelete  = errors.New("cannot delete published hackathon")
	ErrPublishNotReady     = errors.New("at least one track with a case is required")
	ErrAlreadyRegistered   = errors.New("already registered for this hackathon")
	ErrNotRegistered       = errors.New("not registered for this hackathon")
	ErrAlreadyInTeam       = errors.New("already in a team for this hackathon")
	ErrNotInTeam           = errors.New("not in this team")
	ErrTeamFull            = errors.New("team is full")
	ErrNotCaptain          = errors.New("only team captain can perform this action")
	ErrCaptainCannotLeave  = errors.New("captain cannot leave the team")
	ErrDeadlinePassed      = errors.New("submission deadline has passed")
	ErrRegistrationClosed  = errors.New("registration is closed")
	ErrParticipantsOnly    = errors.New("only participants can register for hackathons")
	ErrCaseRequired        = errors.New("team must select a case before submission")
	ErrInTeamBlockUnregister = errors.New("cannot unregister while in a team")
)
